export const SAMPLE_EVENTS = [
  {
    _id: "event-1",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Morning Yoga",
    description: "30-minute yoga session",
    startTime: new Date(new Date().setHours(7, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(7, 30, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "daily",
    location: "Home",
    completionStatus: "scheduled",
  },
  {
    _id: "event-2",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Team Standup",
    description: "Daily team sync meeting",
    startTime: new Date(new Date().setHours(9, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(9, 30, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "daily",
    location: "Zoom",
    completionStatus: "scheduled",
  },
  {
    _id: "event-3",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Deep Work Session",
    description: "Focus time for project development",
    startTime: new Date(new Date().setHours(10, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: undefined,
    location: "Home Office",
    completionStatus: "scheduled",
  },
  {
    _id: "event-4",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Lunch with Sarah",
    description: "Catch up with old friend",
    startTime: new Date(new Date().setHours(12, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(13, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: undefined,
    location: "Local Cafe",
    completionStatus: "scheduled",
  },
  {
    _id: "event-5",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Gym Workout",
    description: "Strength training session",
    startTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(18, 0, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "daily",
    location: "Gym",
    completionStatus: "scheduled",
  },
  {
    _id: "event-6",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Family Dinner",
    description: "Weekly family dinner",
    startTime: new Date(new Date().setHours(19, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(20, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: "weekly",
    location: "Home",
    completionStatus: "scheduled",
  },
];

export const SAMPLE_BUFFERS = [
  {
    id: "buffer-1",
    afterEventId: "event-1",
    startTime: new Date(new Date().setHours(7, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(7, 45, 0, 0)).getTime(),
    duration: 15,
    purpose: "recovery" as const,
    riskReduction: 0.4,
    recommended: true,
  },
  {
    id: "buffer-2",
    afterEventId: "event-2",
    beforeEventId: "event-3",
    startTime: new Date(new Date().setHours(9, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(10, 0, 0, 0)).getTime(),
    duration: 30,
    purpose: "transition" as const,
    riskReduction: 0.3,
    recommended: true,
  },
  {
    id: "buffer-3",
    afterEventId: "event-3",
    beforeEventId: "event-4",
    startTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(12, 30, 0, 0)).getTime(),
    duration: 30,
    purpose: "buffer" as const,
    riskReduction: 0.5,
    recommended: true,
  },
  {
    id: "buffer-4",
    afterEventId: "event-4",
    beforeEventId: "event-5",
    startTime: new Date(new Date().setHours(13, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime(),
    duration: 210,
    purpose: "travel" as const,
    riskReduction: 0.2,
    recommended: false,
  },
  {
    id: "buffer-5",
    afterEventId: "event-5",
    beforeEventId: "event-6",
    startTime: new Date(new Date().setHours(18, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(19, 0, 0, 0)).getTime(),
    duration: 60,
    purpose: "recovery" as const,
    riskReduction: 0.6,
    recommended: true,
  },
];

export const SYSTEM_COLORS = {
  Health: {
    bg: "bg-green-500",
    bgLight: "bg-green-50 dark:bg-green-900/20",
    border: "border-green-500",
    text: "text-green-700 dark:text-green-300",
    hover: "hover:bg-green-50 dark:hover:bg-green-900/30",
  },
  Work: {
    bg: "bg-blue-500",
    bgLight: "bg-blue-50 dark:bg-blue-900/20",
    border: "border-blue-500",
    text: "text-blue-700 dark:text-blue-300",
    hover: "hover:bg-blue-50 dark:hover:bg-blue-900/30",
  },
  Relationships: {
    bg: "bg-purple-500",
    bgLight: "bg-purple-50 dark:bg-purple-900/20",
    border: "border-purple-500",
    text: "text-purple-700 dark:text-purple-300",
    hover: "hover:bg-purple-50 dark:hover:bg-purple-900/30",
  },
};
