export const SAMPLE_EVENTS = [
  {
    _id: "event-1",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Morning Yoga",
    description: "30-minute yoga session for flexibility and mindfulness",
    startTime: new Date(new Date().setHours(7, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(7, 30, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "daily",
    location: "Home",
    completionStatus: "scheduled",
  },
  {
    _id: "event-2",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Team Standup",
    description: "Daily team sync meeting to align on priorities",
    startTime: new Date(new Date().setHours(9, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(9, 30, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "daily",
    location: "Zoom",
    completionStatus: "scheduled",
  },
  {
    _id: "event-3",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Deep Work Session",
    description: "Focus time for project development and coding",
    startTime: new Date(new Date().setHours(10, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: undefined,
    location: "Home Office",
    completionStatus: "scheduled",
  },
  {
    _id: "event-4",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Lunch with Sarah",
    description: "Catch up with old friend over lunch",
    startTime: new Date(new Date().setHours(12, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(13, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: undefined,
    location: "Local Cafe",
    completionStatus: "scheduled",
  },
  {
    _id: "event-5",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Gym Workout",
    description: "Strength training session - Upper body focus",
    startTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(18, 0, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "daily",
    location: "Gym",
    completionStatus: "scheduled",
  },
  {
    _id: "event-6",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Family Dinner",
    description: "Weekly family dinner and catch-up",
    startTime: new Date(new Date().setHours(19, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(20, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: "weekly",
    location: "Home",
    completionStatus: "scheduled",
  },
  {
    _id: "event-7",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Project Planning Meeting",
    description: "Q2 project roadmap and milestone planning",
    startTime: new Date(new Date().setHours(14, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(15, 0, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "weekly",
    location: "Conference Room B",
    completionStatus: "scheduled",
  },
  {
    _id: "event-8",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Meditation",
    description: "10-minute morning meditation and breathing",
    startTime: new Date(new Date().setHours(6, 45, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(6, 55, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "daily",
    location: "Home",
    completionStatus: "scheduled",
  },
  {
    _id: "event-9",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Client Call - TechCorp",
    description: "Monthly check-in and product feedback review",
    startTime: new Date(new Date().setHours(10, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(11, 30, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "monthly",
    location: "Zoom",
    completionStatus: "scheduled",
  },
  {
    _id: "event-10",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Cooking Dinner",
    description: "Meal prep for the week - Italian pasta dishes",
    startTime: new Date(new Date().setHours(18, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(19, 30, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "weekly",
    location: "Home",
    completionStatus: "scheduled",
  },
  {
    _id: "event-11",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Movie Night with Friends",
    description: "Watch new release with college friends",
    startTime: new Date(new Date().setHours(19, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(21, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: undefined,
    location: "Cinema Downtown",
    completionStatus: "scheduled",
  },
  {
    _id: "event-12",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Code Review Session",
    description: "Review pull requests from team members",
    startTime: new Date(new Date().setHours(15, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(16, 30, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "twice-weekly",
    location: "Home Office",
    completionStatus: "scheduled",
  },
  {
    _id: "event-13",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Doctor Checkup",
    description: "Annual health checkup and blood work",
    startTime: new Date(new Date().setHours(8, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(9, 0, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: undefined,
    location: "City Medical Center",
    completionStatus: "scheduled",
  },
  {
    _id: "event-14",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Book Club Discussion",
    description: "Monthly book club - discuss current selection",
    startTime: new Date(new Date().setHours(20, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(21, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: "monthly",
    location: "Library Reading Room",
    completionStatus: "scheduled",
  },
  {
    _id: "event-15",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Product Demo Prep",
    description: "Prepare slides and demo for client presentation",
    startTime: new Date(new Date().setHours(13, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(14, 0, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: undefined,
    location: "Home Office",
    completionStatus: "scheduled",
  },
  {
    _id: "event-16",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Evening Run",
    description: "5K evening jog around the park",
    startTime: new Date(new Date().setHours(18, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(19, 15, 0, 0)).getTime(),
    system: "Health" as const,
    color: "bg-green-500",
    allDay: false,
    recurrence: "three-times-weekly",
    location: "Central Park",
    completionStatus: "scheduled",
  },
  {
    _id: "event-17",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Lunch Meeting with Manager",
    description: "Quarterly performance and career development discussion",
    startTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(13, 0, 0, 0)).getTime(),
    system: "Work" as const,
    color: "bg-blue-500",
    allDay: false,
    recurrence: "quarterly",
    location: "Downtown Restaurant",
    completionStatus: "scheduled",
  },
  {
    _id: "event-18",
    _creationTime: Date.now(),
    userId: "user-1",
    title: "Phone Call with Mom",
    description: "Weekly catch-up call with family",
    startTime: new Date(new Date().setHours(20, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(20, 30, 0, 0)).getTime(),
    system: "Relationships" as const,
    color: "bg-purple-500",
    allDay: false,
    recurrence: "weekly",
    location: "Home",
    completionStatus: "scheduled",
  },
];

export const SAMPLE_BUFFERS = [
  {
    id: "buffer-1",
    afterEventId: "event-8",
    beforeEventId: "event-1",
    startTime: new Date(new Date().setHours(6, 55, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(7, 0, 0, 0)).getTime(),
    duration: 5,
    purpose: "transition" as const,
    riskReduction: 0.2,
    recommended: true,
  },
  {
    id: "buffer-2",
    afterEventId: "event-1",
    beforeEventId: "event-2",
    startTime: new Date(new Date().setHours(7, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(9, 0, 0, 0)).getTime(),
    duration: 90,
    purpose: "recovery" as const,
    riskReduction: 0.5,
    recommended: true,
  },
  {
    id: "buffer-3",
    afterEventId: "event-2",
    beforeEventId: "event-3",
    startTime: new Date(new Date().setHours(9, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(10, 0, 0, 0)).getTime(),
    duration: 30,
    purpose: "transition" as const,
    riskReduction: 0.3,
    recommended: true,
  },
  {
    id: "buffer-4",
    afterEventId: "event-3",
    beforeEventId: "event-4",
    startTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(12, 30, 0, 0)).getTime(),
    duration: 30,
    purpose: "buffer" as const,
    riskReduction: 0.4,
    recommended: true,
  },
  {
    id: "buffer-5",
    afterEventId: "event-4",
    beforeEventId: "event-5",
    startTime: new Date(new Date().setHours(13, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime(),
    duration: 210,
    purpose: "travel" as const,
    riskReduction: 0.2,
    recommended: false,
  },
  {
    id: "buffer-6",
    afterEventId: "event-5",
    beforeEventId: "event-6",
    startTime: new Date(new Date().setHours(18, 0, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(19, 0, 0, 0)).getTime(),
    duration: 60,
    purpose: "recovery" as const,
    riskReduction: 0.6,
    recommended: true,
  },
  {
    id: "buffer-7",
    afterEventId: "event-12",
    beforeEventId: "event-5",
    startTime: new Date(new Date().setHours(16, 30, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime(),
    duration: 30,
    purpose: "transition" as const,
    riskReduction: 0.3,
    recommended: true,
  },
  {
    id: "buffer-8",
    afterEventId: "event-16",
    beforeEventId: "event-6",
    startTime: new Date(new Date().setHours(19, 15, 0, 0)).getTime(),
    endTime: new Date(new Date().setHours(19, 30, 0, 0)).getTime(),
    duration: 15,
    purpose: "recovery" as const,
    riskReduction: 0.4,
    recommended: true,
  },
];

export const SYSTEM_COLORS = {
  Health: {
    bg: "bg-green-500",
    bgLight: "bg-green-50 dark:bg-green-900/20",
    border: "border-green-500",
    text: "text-green-700 dark:text-green-300",
    hover: "hover:bg-green-50 dark:hover:bg-green-900/30",
  },
  Work: {
    bg: "bg-blue-500",
    bgLight: "bg-blue-50 dark:bg-blue-900/20",
    border: "border-blue-500",
    text: "text-blue-700 dark:text-blue-300",
    hover: "hover:bg-blue-50 dark:hover:bg-blue-900/30",
  },
  Relationships: {
    bg: "bg-purple-500",
    bgLight: "bg-purple-50 dark:bg-purple-900/20",
    border: "border-purple-500",
    text: "text-purple-700 dark:text-purple-300",
    hover: "hover:bg-purple-50 dark:hover:bg-purple-900/30",
  },
};
